name: Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

       # Change to the directory containing the mvnw file
      - name: Navigate to hello-world/hello-world directory
        run: cd hello-world/hello-world

      - name: Build with Maven
        run: ./mvnw clean install -U




        
      
